# -*- coding: utf-8 -*-
"""
Created on Wed Oct  9 12:25:15 2024

@author: umroot
"""

import aviary.api as av



phase_info = {
    "pre_mission": {"include_takeoff": False, "optimize_mass": True},
    "climb_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "num_segments": 3,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.2, "unitless"),
            "final_mach": (0.72, "unitless"),
            "mach_bounds": ((0.18, 0.74), "unitless"),
            "initial_altitude": (0.0, "ft"),
            "final_altitude": (31000.0, "ft"),
            "altitude_bounds": ((0.0, 31500.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": True,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((0.0, 0.0), "min"),
            "duration_bounds": ((25.5, 76.5), "min"),
        },
        "initial_guesses": {"time": ([0, 51], "min")},
    },
    "cruise_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "num_segments": 3,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.72, "unitless"),
            "final_mach": (0.72, "unitless"),
            "mach_bounds": ((0.7, 0.74), "unitless"),
            "initial_altitude": (31000.0, "ft"),
            "final_altitude": (31000.0, "ft"),
            "altitude_bounds": ((30500.0, 31500.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((25.5, 76.5), "min"),
            "duration_bounds": ((23.5, 70.5), "min"),
        },
        "initial_guesses": {"time": ([51, 47], "min")},
    },
    "climb_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "num_segments": 3,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.72, "unitless"),
            "final_mach": (0.74, "unitless"),
            "mach_bounds": ((0.7, 0.76), "unitless"),
            "initial_altitude": (31000.0, "ft"),
            "final_altitude": (33000.0, "ft"),
            "altitude_bounds": ((30500.0, 33500.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((49.0, 147.0), "min"),
            "duration_bounds": ((5.0, 15.0), "min"),
        },
        "initial_guesses": {"time": ([98, 10], "min")},
    },
    "cruise_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "num_segments": 3,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.74, "unitless"),
            "final_mach": (0.74, "unitless"),
            "mach_bounds": ((0.72, 0.76), "unitless"),
            "initial_altitude": (33000.0, "ft"),
            "final_altitude": (33000.0, "ft"),
            "altitude_bounds": ((32500.0, 33500.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((54.0, 162.0), "min"),
            "duration_bounds": ((24.0, 72.0), "min"),
        },
        "initial_guesses": {"time": ([108, 48], "min")},
    },
    "climb_3": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "num_segments": 3,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.74, "unitless"),
            "final_mach": (0.76, "unitless"),
            "mach_bounds": ((0.72, 0.78), "unitless"),
            "initial_altitude": (33000.0, "ft"),
            "final_altitude": (34500.0, "ft"),
            "altitude_bounds": ((32500.0, 35000.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((78.0, 234.0), "min"),
            "duration_bounds": ((7.0, 21.0), "min"),
        },
        "initial_guesses": {"time": ([156, 14], "min")},
    },
    "climb_4": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "num_segments": 3,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.76, "unitless"),
            "final_mach": (0.76, "unitless"),
            "mach_bounds": ((0.74, 0.78), "unitless"),
            "initial_altitude": (34500.0, "ft"),
            "final_altitude": (36000.0, "ft"),
            "altitude_bounds": ((34000.0, 36500.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((85.0, 255.0), "min"),
            "duration_bounds": ((43.0, 129.0), "min"),
        },
        "initial_guesses": {"time": ([170, 86], "min")},
    },
    "descent_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "num_segments": 3,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.76, "unitless"),
            "final_mach": (0.2, "unitless"),
            "mach_bounds": ((0.18, 0.78), "unitless"),
            "initial_altitude": (36000.0, "ft"),
            "final_altitude": (500.0, "ft"),
            "altitude_bounds": ((0.0, 36500.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": False,
            "constrain_final": True,
            "fix_duration": False,
            "initial_bounds": ((128.0, 384.0), "min"),
            "duration_bounds": ((41.0, 123.0), "min"),
        },
        "initial_guesses": {"time": ([256, 82], "min")},
    },
    "post_mission": {
        "include_landing": False,
        "constrain_range": True,
        "target_range": (2393, "nmi"),
    },
}

prob = av.run_aviary('models/test_aircraft/aircraft_for_bench_FwFm.csv',
                    phase_info, optimizer="SLSQP", make_plots=True)