# -*- coding: utf-8 -*-
"""
Created on Thu Dec  5 22:26:24 2024

@author: User
"""

import aviary.api as av
#from brac_phase_info import phase_info
import openmdao.api as om
import sqlite3
import pandas as pd

# Define phase information, adding aerodynamic variables to output
phase_info = {
    "pre_mission": {"include_takeoff": False, "optimize_mass": False},

    # "climb_1": {
    #     "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
    #     "user_options": {
    #         "optimize_mach": False,
    #         "optimize_altitude": False,
    #         "polynomial_control_order": 1,
    #         "use_polynomial_control": True,
    #         "num_segments": 7,
    #         "order": 3,
    #         "solve_for_distance": False,
    #         "initial_mach": (0.25, "unitless"),
    #         "final_mach": (0.4, "unitless"),
    #         "mach_bounds": ((0.23, 0.42), "unitless"),
    #         "initial_altitude": (0.0, "ft"),
    #         "final_altitude": (11700.0, "ft"),
    #         "altitude_bounds": ((0.0, 12200.0), "ft"),
    #         "throttle_enforcement": "boundary_constraint",
    #         "fix_initial": False,
    #         "constrain_final": False,
    #         "fix_duration": False,
    #         "initial_bounds": ((0.0, 0.0), "min"),
    #         "duration_bounds": ((3.0, 4.5), "min"),
    #     },
    #     "initial_guesses": {"time": ([0.0, 3.75], "min")},
    # },
    # "climb_2": {
    #     "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
    #     "user_options": {
    #         "optimize_mach": False,
    #         "optimize_altitude": False,
    #         "polynomial_control_order": 1,
    #         "use_polynomial_control": True,
    #         "num_segments": 7,
    #         "order": 3,
    #         "solve_for_distance": False,
    #         "initial_mach": (0.4, "unitless"),
    #         "final_mach": (0.8, "unitless"),
    #         "mach_bounds": ((0.38, 0.82), "unitless"),
    #         "initial_altitude": (11700.0, "ft"),
    #         "final_altitude": (41000.0, "ft"),
    #         "altitude_bounds": ((11200.0, 41200.0), "ft"),
    #         "throttle_enforcement": "boundary_constraint",
    #         "fix_initial": False,
    #         "constrain_final": False,
    #         "fix_duration": False,
    #         "initial_bounds": ((3.0, 4.5), "min"),
    #         "duration_bounds": ((16.0, 24.0), "min"),
    #     },
    #     "initial_guesses": {"time": ([3.75, 20.5], "min")},
    # },
    # "cruise_1": {
    #     "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
    #     "user_options": {
    #         "optimize_mach": False,
    #         "optimize_altitude": False,
    #         "polynomial_control_order": 1,
    #         "use_polynomial_control": True,
    #         "num_segments": 7,
    #         "order": 3,
    #         "solve_for_distance": False,
    #         "initial_mach": (0.8, "unitless"),
    #         "final_mach": (0.784, "unitless"),
    #         "mach_bounds": ((0.82, 0.764), "unitless"),
    #         "initial_altitude": (41000.0, "ft"),
    #         "final_altitude": (39000.0, "ft"),
    #         "altitude_bounds": ((40500.0, 39500.0), "ft"),
    #         "throttle_enforcement": "boundary_constraint",
    #         "fix_initial": False,
    #         "constrain_final": False,
    #         "fix_duration": False,
    #         "initial_bounds": ((16.0, 24.0), "min"),
    #         "duration_bounds": ((90.0, 100.0), "min"),
    #     },
    #     "initial_guesses": {"time": ([20.5, 96.25], "min")},
    # },
    # "descent_1": {
    #     "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
    #     "user_options": {
    #         "optimize_mach": False,
    #         "optimize_altitude": False,
    #         "polynomial_control_order": 1,
    #         "use_polynomial_control": True,
    #         "num_segments": 7,
    #         "order": 3,
    #         "solve_for_distance": False,
    #         "initial_mach": (0.784, "unitless"),
    #         "final_mach": (0.568, "unitless"),
    #         "mach_bounds": ((0.804, 0.548), "unitless"),
    #         "initial_altitude": (39000.0, "ft"),
    #         "final_altitude": (12700.0, "ft"),
    #         "altitude_bounds": ((38800, 13200.0), "ft"),
    #         "throttle_enforcement": "boundary_constraint",
    #         "fix_initial": False,
    #         "constrain_final": False,
    #         "fix_duration": False,
    #         "initial_bounds": ((90.0, 100.0), "min"),
    #         "duration_bounds": ((110.0, 120.0), "min"),
    #     },
    #     "initial_guesses": {"time": ([96.25, 115.75], "min")},
    # },
    # "descent_2": {
    #     "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
    #     "user_options": {
    #         "optimize_mach": False,
    #         "optimize_altitude": False,
    #         "polynomial_control_order": 1,
    #         "use_polynomial_control": True,
    #         "num_segments": 7,
    #         "order": 3,
    #         "solve_for_distance": False,
    #         "initial_mach": (0.568, "unitless"),
    #         "final_mach": (0.364, "unitless"),
    #         "mach_bounds": ((0.588, 0.344), "unitless"),
    #         "initial_altitude": (12700.0, "ft"),
    #         "final_altitude": (2700.0, "ft"),
    #         "altitude_bounds": ((12900, 1500.0), "ft"),
    #         "throttle_enforcement": "boundary_constraint",
    #         "fix_initial": False,
    #         "constrain_final": False,
    #         "fix_duration": False,
    #         "initial_bounds": ((110.0, 120.0), "min"),
    #         "duration_bounds": ((115.0, 123.0), "min"),
    #     },
    #     "initial_guesses": {"time": ([115.75, 122.75], "min")},
    # },
    # "descent_3": {
    #     "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
    #     "user_options": {
    #         "optimize_mach": False,
    #         "optimize_altitude": False,
    #         "polynomial_control_order": 1,
    #         "use_polynomial_control": True,
    #         "num_segments": 7,
    #         "order": 3,
    #         "solve_for_distance": False,
    #         "initial_mach": (0.364, "unitless"),
    #         "final_mach": (0.362, "unitless"),
    #         "mach_bounds": ((0.384, 0.342), "unitless"),
    #         "initial_altitude": (2700.0, "ft"),
    #         "final_altitude": (1700.0, "ft"),
    #         "altitude_bounds": ((2900.0, 1500.0), "ft"),
    #         "throttle_enforcement": "path_constraint",
    #         "fix_initial": False,
    #         "constrain_final": True,
    #         "fix_duration": False,
    #         "initial_bounds": ((115.0, 122.0), "min"),
    #         "duration_bounds": ((123.0, 124.0), "min"),
    #     },
    #     "initial_guesses": {"time": ([122.75, 123.58], "min")},
    # },
    # "descent_4": {
    #     "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
    #     "user_options": {
    #         "optimize_mach": False,
    #         "optimize_altitude": False,
    #         "polynomial_control_order": 1,
    #         "use_polynomial_control": True,
    #         "num_segments": 7,
    #         "order": 3,
    #         "solve_for_distance": False,
    #         "initial_mach": (0.332, "unitless"),
    #         "final_mach": (0.25, "unitless"),
    #         "mach_bounds": ((0.352, 0.23), "unitless"),
    #         "initial_altitude": (1700.0, "ft"),
    #         "final_altitude": (0.0, "ft"),
    #         "altitude_bounds": ((1900.0, 0.0), "ft"),
    #         "throttle_enforcement": "path_constraint",
    #         "fix_initial": False,
    #         "constrain_final": True,
    #         "fix_duration": False,
    #         "initial_bounds": ((123.0, 124.0), "min"),
    #         "duration_bounds": ((126.5, 130.5), "min"),
    #     },
    #     "initial_guesses": {"time": ([123.58, 128.88], "min")},
    # },
    "climb_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.25, "unitless"),
            "final_mach": (0.4, "unitless"),
            "mach_bounds": ((0.23, 0.42), "unitless"),
            "initial_altitude": (0.0, "ft"),
            "final_altitude": (3475.0, "ft"),
            "altitude_bounds": ((0.0, 3675.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((0.0, 0.0), "min"),
            "duration_bounds": ((1.0, 2.5), "min"),
        },
        "initial_guesses": {"time": ([0.0, 1.58], "min")},
    },
    "climb_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.408, "unitless"),
            "final_mach": (0.42, "unitless"),
            "mach_bounds": ((0.388, 0.44), "unitless"),
            "initial_altitude": (3475.0, "ft"),
            "final_altitude": (7500.0, "ft"),
            "altitude_bounds": ((3275.0, 7700.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((1.0, 2.5), "min"),
            "duration_bounds": ((3.5, 4.0), "min"),
        },
        "initial_guesses": {"time": ([1.58, 3.75], "min")},
    },
    "cruise_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.42, "unitless"),
            "final_mach": (0.436, "unitless"),
            "mach_bounds": ((0.40, 0.456), "unitless"),
            "initial_altitude": (7500.0, "ft"),
            "final_altitude": (7500.0, "ft"),
            "altitude_bounds": ((7300.0, 7700.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((3.5, 4.0), "min"),
            "duration_bounds": ((7.0, 8.0), "min"),
        },
        "initial_guesses": {"time": ([3.75, 7.66], "min")},
    },
    "cruise_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.416, "unitless"),
            "final_mach": (0.412, "unitless"),
            "mach_bounds": ((0.396, 0.432), "unitless"),
            "initial_altitude": (6475.0, "ft"),
            "final_altitude": (6475.0, "ft"),
            "altitude_bounds": ((6275.0, 6675.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((7.0, 8.0), "min"),
            "duration_bounds": ((12.0, 16.0), "min"),
        },
        "initial_guesses": {"time": ([7.66, 13.9], "min")},
    },
    "cruise_3": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.408, "unitless"),
            "final_mach": (0.412, "unitless"),
            "mach_bounds": ((0.388, 0.432), "unitless"),
            "initial_altitude": (5475.0, "ft"),
            "final_altitude": (5475.0, "ft"),
            "altitude_bounds": ((5275, 5675.0), "ft"),
            "throttle_enforcement": "boundary_constraint",
            "fix_initial": False,
            "constrain_final": False,
            "fix_duration": False,
            "initial_bounds": ((12.0, 16.0), "min"),
            "duration_bounds": ((16.0, 19.0), "min"),
        },
        "initial_guesses": {"time": ([13.9, 17.24], "min")},
    },
    "descent_1": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.412, "unitless"),
            "final_mach": (0.3, "unitless"),
            "mach_bounds": ((0.432, 0.28), "unitless"),
            "initial_altitude": (5475.0, "ft"),
            "final_altitude": (1875.0, "ft"),
            "altitude_bounds": ((5675.0, 1675.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": False,
            "constrain_final": True,
            "fix_duration": False,
            "initial_bounds": ((16.0, 19.0), "min"),
            "duration_bounds": ((17.0, 22.0), "min"),
        },
        "initial_guesses": {"time": ([17.24, 20.4], "min")},
    },
    "descent_2": {
        "subsystem_options": {"core_aerodynamics": {"method": "computed"}},
        "user_options": {
            "optimize_mach": False,
            "optimize_altitude": False,
            "polynomial_control_order": 1,
            "use_polynomial_control": True,
            "num_segments": 7,
            "order": 3,
            "solve_for_distance": False,
            "initial_mach": (0.3, "unitless"),
            "final_mach": (0.25, "unitless"),
            "mach_bounds": ((0.32, 0.23), "unitless"),
            "initial_altitude": (1875.0, "ft"),
            "final_altitude": (175.0, "ft"),
            "altitude_bounds": ((2075.0, 0.0), "ft"),
            "throttle_enforcement": "path_constraint",
            "fix_initial": False,
            "constrain_final": True,
            "fix_duration": False,
            "initial_bounds": ((17.0, 22.0), "min"),
            "duration_bounds": ((22.0, 24.0), "min"),
        },
        "initial_guesses": {"time": ([20.4, 23.2], "min")},
    },
    "post_mission": {
        "include_landing": False,
        "constrain_range": True,
        "target_range": (3100, "nmi"),
    },
}


prob = av.AviaryProblem()

# Load aircraft and options data from user
# Allow for user overrides here
prob.load_inputs('brac_aircraft.csv', phase_info)

prob.check_and_preprocess_inputs()

prob.add_pre_mission_systems()

prob.add_phases()

prob.add_post_mission_systems()

# Link phases and variables
prob.link_phases()

prob.add_driver("SLSQP", max_iter=1000)

prob.add_design_variables()

prob.add_objective(objective_type="mass", ref=-1e5)

prob.setup()

prob.set_initial_guesses()

prob.run_aviary_problem(record_filename='brac_level2.db', suppress_solver_print=True, make_plots=True)